services:
  - type: web
    name: pokelore-net
    runtime: static
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    routes:
      - type: redirect
        source: /pokemon/25
        destination: /pokemon/pikachu
      - type: redirect
        source: /pokemon/131
        destination: /pokemon/lapras
      - type: rewrite
        source: /pokemon/pikachu
        destination: /pokemon/pikachu/index.html
      - type: rewrite
        source: /pokemon/lapras
        destination: /pokemon/lapras/index.html
      - type: rewrite
        source: /pokemon/*
        destination: /index.html
      - type: rewrite
        source: /*
        destination: /index.html
