import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { POKEMON_SLUG_SET } from './routes.js';
import { MOVE_SLUG_SET } from './moveData.js';
const root = resolve(process.cwd(), '..'); const dataDir = join(root, 'public', 'data');
const read = file => JSON.parse(readFileSync(join(dataDir, file), 'utf8'));
const releasedDynamax = new Set(['dynamax-crystal-charizard','dynamax-crystal-gengar','dynamax-crystal-kingler','dynamax-crystal-lapras','dynamax-crystal-kyogre','dynamax-crystal-groudon','dynamax-crystal-rayquaza','dynamax-crystal-reshiram','dynamax-crystal-zekrom','dynamax-crystal-eternatus','dynamax-crystal-duraludon','dynamax-crystal-snorlax']);
const hidden = item => item.category?.name === 'dynamax-crystals' && !releasedDynamax.has(item.name);
const source = readdirSync(join(dataDir, 'items')).filter(file => file.endsWith('.json')).map(file => read(join('items', file))).filter(item => !hidden(item));
export const ITEM_SLUGS = Object.freeze(source.map(item => item.name).sort((a,b) => a.localeCompare(b))); export const ITEM_SLUG_SET = new Set(ITEM_SLUGS);
export const ITEM_STRESS_SLUGS = Object.freeze(['leftovers','oran-berry','fire-stone','reaper-cloth','master-ball','potion','x-attack','old-amber','tm01','hm01','tr01','charizardite-x','firium-z--bag','flame-plate','fighting-memory','douse-drive','lax-incense','ability-patch','zygarde-cube','zangoose-claw']);
export const ITEM_REGISTRY = Object.freeze(source.map(item => ({ slug:item.name, id:item.id, displayName:item.displayName, category:item.category?.name ?? null, pocket:item.category?.pocket ?? null })));
const bySlug = new Map(source.map(item => [item.name, item])); const optional=(dir,slug)=>{const file=join(dataDir,dir,`${slug}.json`);return existsSync(file)?JSON.parse(readFileSync(file,'utf8')):null};
let evolutionRules=[]; try { ({ evolutionItemRules:evolutionRules } = await import('../../../src/data/itemSpecializationRules.js')); } catch {}
const display=value=>String(value??'').split('-').filter(Boolean).map(word=>word[0]?.toUpperCase()+word.slice(1)).join(' ');
export function itemModel(slug){const item=bySlug.get(slug);if(!item)return null;const heldByPokemon=(item.heldByPokemon??[]).map(row=>row.pokemon).filter(name=>POKEMON_SLUG_SET.has(name)).map(name=>({name,displayName:display(name)}));const machines=(item.machines??[]).filter(row=>row.move?.name&&MOVE_SLUG_SET.has(row.move.name)).map(row=>({...row,move:{...row.move,displayName:display(row.move.name)}}));const evolution=evolutionRules.filter(rule=>rule.item===slug&&POKEMON_SLUG_SET.has(rule.sourceSlug)&&POKEMON_SLUG_SET.has(rule.targetSlug)).map(rule=>({...rule,sourceDisplayName:display(rule.sourceSlug),targetDisplayName:display(rule.targetSlug)}));const berry=item.category?.pocket==='berries'?optional('berries/generated/details',slug):null;const acquisition=optional('itemLocationsCurated',slug);const effect=machines.length?`${item.displayName} teaches ${[...new Set(machines.map(row=>display(row.move.name)))].join(', ')}.`:item.effect;const canonical=`https://pokelore.net/item/${slug}`,description=`View the ${item.displayName} item details, effect, category, and related Pokémon and moves on PokéLore.`;return {...item,slug,displayName:item.displayName??display(slug),effect,shortEffect:item.shortEffect??item.effect,heldByPokemon,machines,evolution,berry,acquisition,oaksNotes:optional('oaksNotes/items',slug),canonical,seo:{title:`${item.displayName??display(slug)} Item Guide | PokéLore`,description,canonical,structuredData:{'@context':'https://schema.org','@graph':[{ '@type':'WebPage','@id':`${canonical}#webpage`,url:canonical,name:`${item.displayName??display(slug)} Item Guide`,description,mainEntity:{'@id':`${canonical}#item`}},{'@type':'Thing','@id':`${canonical}#item`,name:item.displayName??display(slug),description:item.effect??item.shortEffect??description},{'@type':'BreadcrumbList','@id':`${canonical}#breadcrumb`,itemListElement:[{'@type':'ListItem',position:1,name:'PokéLore',item:'https://pokelore.net/'},{'@type':'ListItem',position:2,name:'Items',item:'https://pokelore.net/items'},{'@type':'ListItem',position:3,name:item.displayName??display(slug),item:canonical}]}]}}};}
export function allItemModels(){return ITEM_SLUGS.map(itemModel)}
