import { getRoute119FeebasCoordinateForSpotId } from "./rseFeebasCalculator";

export const RSE_UNREACHABLE_SPOT_IDS = new Set([
  105,
  119,
  144,
  296,
  297,
  298
]);

export const RSE_UNDER_BRIDGE_SPOT_ID = 132;

export const RSE_UNDER_BRIDGE_DISPLAY_COORDINATES = [
  { x: 16, y: 17 },
  { x: 17, y: 17 },
  { x: 18, y: 17 },
  { x: 19, y: 17 },
  { x: 20, y: 17 },
  { x: 16, y: 18 },
  { x: 17, y: 18 },
  { x: 18, y: 18 },
  { x: 19, y: 18 },
  { x: 20, y: 18 }
];

export const RSE_SPOT_DISPLAY_OVERRIDES = {
  [RSE_UNDER_BRIDGE_SPOT_ID]: {
    type: "underBridge",
    label: "Under bridge",
    coordinates: RSE_UNDER_BRIDGE_DISPLAY_COORDINATES
  }
};

// Route 119 internal Feebas spot IDs are not perfectly one-to-one with
// player-fishable map locations. IDs 105, 119, 144, 296, 297 and 298 may be
// generated by the game, but their raw positions are inaccessible. ID 132 is
// a special under-bridge result represented by multiple player-fishable
// positions. Do not remove or renumber these IDs in the canonical mapping.
export function getPlayerFacingLocationsForSpotId(
  spotId
) {
  const normalizedSpotId = Number(spotId);

  if (RSE_UNREACHABLE_SPOT_IDS.has(normalizedSpotId)) {
    return [];
  }

  const override =
    RSE_SPOT_DISPLAY_OVERRIDES[normalizedSpotId];
  if (override) {
    return override.coordinates.map((coordinate, index) => ({
      ...coordinate,
      spotId: normalizedSpotId,
      sourceSpotId: normalizedSpotId,
      displayRule: override.type,
      displayRuleLabel: override.label,
      displayIndex: index + 1,
      feebasSelectable: true
    }));
  }

  const tile =
    getRoute119FeebasCoordinateForSpotId(
      normalizedSpotId
    );

  if (!tile || tile.feebasSelectable === false) {
    return [];
  }

  return [
    {
      ...tile,
      sourceSpotId: normalizedSpotId,
      displayRule: "canonical",
      displayRuleLabel: "Canonical"
    }
  ];
}

export function getPlayerFacingLocationsForSpotIds(
  spotIds
) {
  return spotIds.flatMap((spotId, resultIndex) =>
    getPlayerFacingLocationsForSpotId(spotId).map(
      location => ({
        ...location,
        resultNumber: resultIndex + 1
      })
    )
  );
}
