import { chromium } from '../../node_modules/playwright/index.mjs';
import { mkdirSync, writeFileSync, readFileSync, readdirSync } from 'node:fs';
import { gzipSync } from 'node:zlib';
import assert from 'node:assert/strict';
const origin='http://127.0.0.1:4321';
mkdirSync('evidence/phase1b',{recursive:true});
const browser=await chromium.launch({headless:true});
const errors=[], result={};
try {
  const context=await browser.newContext({viewport:{width:1440,height:1000}});
  await context.addInitScript(()=>{window.__merchEvents=[];window.gtag=(...args)=>window.__merchEvents.push(args);});
  const page=await context.newPage();
  page.on('pageerror',e=>errors.push(e.message));
  page.on('console',m=>{if(m.type()==='error' && /hydration|Minified React|hydrating/i.test(m.text()))errors.push(m.text());});
  await page.goto(`${origin}/pokemon/kakuna`);
  await page.waitForFunction(()=>!document.querySelector('astro-island')?.hasAttribute('ssr'));
  const initialHead=await page.locator('head').evaluate(el=>({title:document.title,canonical:el.querySelector('link[rel=canonical]').href}));
  await page.getByLabel('Global search').fill('pikachu');
  const pikachu=page.locator('header a[href="/pokemon/pikachu"]');
  await pikachu.waitFor();
  await pikachu.click();
  await page.waitForURL('**/pokemon/pikachu');
  await page.goBack(); await page.waitForURL('**/pokemon/kakuna');
  await page.goForward(); await page.waitForURL('**/pokemon/pikachu');
  await page.goBack(); await page.waitForURL('**/pokemon/kakuna');
  await page.locator('.site-menu>summary').click();
  assert(await page.locator('.site-menu a[href="https://pokelore.net/moves"]').isVisible());
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('.site-menu').getAttribute('open'),null);
  for(const id of ['analysis','dex-entries','biology']) {
    await page.locator(`#${id}>summary`).click();
    assert(await page.locator(`#${id} .accordion-body`).isVisible());
  }
  await page.locator('#learnset').scrollIntoViewIfNeeded();
  await page.waitForFunction(()=>!document.querySelector('#learnset astro-island').hasAttribute('ssr'));
  await page.locator('#learnset summary').click();
  const selector=page.getByLabel('Learnset version');
  assert.equal(await selector.inputValue(),'all');
  assert(await page.getByRole('heading',{name:'Tutor',exact:true}).isVisible());
  await selector.selectOption('brilliant-diamond-shining-pearl');
  assert.equal(await page.locator('#learnset a[href$="/move/harden"]').count(),2);
  assert.equal(await page.locator('#learnset a[href$="/move/bug-bite"]').count(),0);
  await page.reload();
  await page.locator('#learnset').scrollIntoViewIfNeeded();
  await page.waitForFunction(()=>document.querySelector('[aria-label="Learnset version"]').value==='brilliant-diamond-shining-pearl');
  assert(await page.getByLabel('Learnset version').isVisible(),'Learnset expansion persisted');
  await page.locator('#encounters').scrollIntoViewIfNeeded();
  await page.waitForFunction(()=>!document.querySelector('#encounters astro-island').hasAttribute('ssr'));
  await page.locator('#encounters>astro-island>details>summary').click();
  await page.getByLabel('Encounter version').selectOption('silver');
  const loc=page.locator('#encounters .accordion-body details').first();
  await loc.locator('summary').focus(); await page.keyboard.press('Enter');
  assert((await loc.textContent()).includes('Silver'));
  assert(!((await page.locator('#encounters .accordion-body details').allTextContents()).join(' ').includes('SoulSilver')));
  assert((await loc.locator('a').first().getAttribute('href')).startsWith('https://pokelore.net/location/'));
  assert.equal(await page.locator('#abilities a').first().getAttribute('href'),'https://pokelore.net/ability/shed-skin');
  assert.equal(await page.locator('#evolution a.pokemon-summary-card').first().getAttribute('href'),'https://pokelore.net/pokemon/weedle');
  // Test optional remote-gallery success/error deterministically, without depending on network availability.
  let apiCalls=0;
  await page.route('https://pokeapi.co/api/v2/pokemon/14',route=>{apiCalls++;return route.fulfill({json:{sprites:{front_default:`${origin}/images/pokemon/official/detail/14.webp`}}});});
  await page.locator('#additional-images').scrollIntoViewIfNeeded();
  await page.waitForFunction(()=>!document.querySelector('#additional-images astro-island').hasAttribute('ssr'));
  await page.locator('#additional-images summary').click();
  await page.locator('#additional-images figure img').waitFor();
  assert.equal(apiCalls,1);
  await page.locator('.etsy-merch-promo').scrollIntoViewIfNeeded();
  await page.waitForFunction(()=>window.__merchEvents.some(args=>args[1]==='etsy_merch_impression'));
  await page.locator('.etsy-merch-promo__link').evaluate(el=>el.addEventListener('click',e=>e.preventDefault()));
  await page.locator('.etsy-merch-promo__link').click();
  assert(await page.evaluate(()=>window.__merchEvents.some(args=>args[1]==='etsy_merch_click')));
  await page.locator('#size-comparison').scrollIntoViewIfNeeded();
  await page.waitForFunction(()=>!document.querySelector('#size-comparison').closest('astro-island').hasAttribute('ssr'));
  const trainer=page.getByLabel('Compare with');
  const options=await trainer.locator('option').evaluateAll(es=>es.map(e=>e.value));
  await trainer.selectOption(options[1]); assert.equal(await trainer.inputValue(),options[1]);
  const layer=page.locator('#size-comparison button').filter({hasText:/front|layer/i}).first();
  if(await layer.count()) await layer.click();
  await page.locator('#size-comparison').screenshot({path:'evidence/phase1b/astro-size-desktop.png'});
  await page.locator('#navigation').scrollIntoViewIfNeeded();
  await page.waitForFunction(()=>!document.querySelector('#navigation astro-island').hasAttribute('ssr'));
  await page.getByRole('button',{name:'Recenter',exact:true}).click();
  assert(await page.locator('#navigation [data-pokemon-name="kakuna"]').isVisible());
  const finalHead=await page.locator('head').evaluate(el=>({title:document.title,canonical:el.querySelector('link[rel=canonical]').href}));
  assert.deepEqual(finalHead,initialHead);
  result.functional='search navigation/back/forward, menu/Escape, native accordions, learnset filter/persistence, encounters, mocked gallery success, trainer selection, navigation recenter, unchanged SEO passed';
  const failPage=await context.newPage();let failedCalls=0;
  await failPage.route('https://pokeapi.co/api/v2/pokemon/14',r=>{failedCalls++;return r.fulfill({status:503,body:'Unavailable'});});
  await failPage.goto(`${origin}/pokemon/kakuna`);
  await failPage.locator('#additional-images').scrollIntoViewIfNeeded();
  await failPage.waitForFunction(()=>!document.querySelector('#additional-images astro-island').hasAttribute('ssr'));
  await failPage.locator('#additional-images summary').click();
  await failPage.getByRole('button',{name:'Retry images'}).waitFor();
  await failPage.waitForTimeout(500);assert.equal(failedCalls,1,'No automatic failure loop');
  await failPage.getByRole('button',{name:'Retry images'}).click();
  await failPage.waitForTimeout(500);assert.equal(failedCalls,2);
  await failPage.close();
  result.galleryFailure='single failed request, explicit retry passed';
  for(const slug of ['kakuna','pikachu','charizard','raichu-alola']) {
    const nojs=await browser.newContext({javaScriptEnabled:false,viewport:{width:390,height:844}});
    const p=await nojs.newPage();await p.goto(`${origin}/pokemon/${slug}`);
    for(const id of ['analysis','dex-entries','biology']) await p.locator(`#${id}>summary`).click();
    for(const id of ['learnset','encounters']) await p.locator(`#${id}>astro-island>details>summary`).click();
    for(const id of ['analysis','biology','learnset','encounters']) assert(await p.locator(`#${id} .accordion-body`).isVisible(),`${slug}: no-JS ${id}`);
    assert(await p.locator('#learnset a[href*="/move/"]').count()>0);
    assert(await p.locator('#abilities p').count()>0);
    assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${slug}: no-JS mobile overflow`);
    result[slug]='no-JS core and native accordions passed';await nojs.close();
    await page.goto(`${origin}/pokemon/${slug}`);
    await page.locator('#learnset').scrollIntoViewIfNeeded();
    await page.waitForFunction(()=>!document.querySelector('#learnset astro-island').hasAttribute('ssr'));
    await page.locator('#size-comparison').scrollIntoViewIfNeeded();
    await page.waitForFunction(()=>!document.querySelector('#size-comparison').closest('astro-island').hasAttribute('ssr'));
    assert(await page.getByLabel('Compare with').count()===1);
  }
  for(const width of [390,900]) {
    await page.setViewportSize({width,height:900});await page.goto(`${origin}/pokemon/kakuna`);
    await page.locator('#size-comparison').scrollIntoViewIfNeeded();await page.waitForTimeout(500);
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    await page.locator('#size-comparison').screenshot({path:`evidence/phase1b/astro-size-${width}.png`});
  }
  assert.deepEqual(errors,[],'No page exceptions/hydration failures');
  const js=readdirSync('dist/_astro').filter(f=>f.endsWith('.js')).map(file=>{const b=readFileSync(`dist/_astro/${file}`);return {file,bytes:b.length,gzip:gzipSync(b).length};});
  result.javascript=js;result.errors=errors;
  writeFileSync('evidence/phase1b/test-results.json',JSON.stringify(result,null,2));
  console.log(JSON.stringify({...result,javascript:{chunks:js.length,bytes:js.reduce((s,f)=>s+f.bytes,0),gzip:js.reduce((s,f)=>s+f.gzip,0)}}));
} finally {await browser.close();}

