import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const origin = process.env.TCG_TEST_ORIGIN ?? 'http://127.0.0.1:5187';
const browser = await chromium.launch({ headless: true });
const context = await browser.newContext({ viewport: { width: 1365, height: 900 } });
const page = await context.newPage();
const errors = []; const requests = [];
page.on('pageerror', e => errors.push(e.message));
page.on('request', request => requests.push(request.url()));
const key = 'pokelore:tcg-challenges:v1';
const getSave = () => page.evaluate(key => JSON.parse(localStorage.getItem(key)), key);
try {
  // Exercise the fallback deliberately; TCGdex's asset host may be unavailable.
  await page.route('https://assets.tcgdex.net/**', route => route.abort());
  await page.goto(`${origin}/tcg-challenge?game=emerald&set=base1&seed=A7D92C18`);
  await page.getByRole('button', { name: 'Start Challenge', exact: true }).waitFor();
  await page.waitForFunction(() => document.querySelector('select') && document.querySelectorAll('select')[1].options.length === 11);
  assert.equal(await page.locator('link[rel=canonical]').getAttribute('href'), 'https://pokelore.net/tcg-challenge');
  assert.equal(await page.locator('meta[name=robots]').getAttribute('content'), 'noindex,follow');
  await page.getByRole('button', { name: 'Start Challenge', exact: true }).click();
  await page.getByRole('button', { name: 'Open Pack', exact: true }).click();
  await page.getByRole('button', { name: 'Reveal card 1 of 11', exact: true }).click();
  assert.equal((await getSave())[0].packs[0].revealed, 1);
  assert.equal(await page.getByRole('button', { name: 'Open next pack' }).isDisabled(), true);
  await page.reload();
  await page.getByRole('button', { name: 'Resume', exact: true }).click();
  await page.getByRole('button', { name: 'Reveal card 2 of 11' }).waitFor();
  await page.getByRole('button', { name: 'Reveal all', exact: true }).click();
  const first = (await getSave())[0].packs[0].cards;
  await page.getByRole('button', { name: /^Add / }).first().click();
  assert.equal((await getSave())[0].team.length, 1);
  await page.getByLabel('Challenge name', { exact: true }).fill('Saved browser test');
  await page.getByLabel('Badges, milestones & your house rules').fill('One badge earned');
  const analysis = page.getByRole('link', { name: 'Analyze this team →' });
  assert.match(await analysis.getAttribute('href'), /version=emerald&team=\d+/);
  await page.getByRole('button', { name: 'Learnset & game info' }).click();
  await page.getByRole('heading', { name: 'Level-up moves', exact: true }).waitFor();
  await page.getByRole('button', { name: 'Close details' }).click();
  await page.getByText('Eligible TMs', { exact: true }).first().click();
  await page.locator('.tcg-tm-list a').first().waitFor();
  await page.locator('.tcg-card').first().scrollIntoViewIfNeeded();
  await page.waitForFunction(() => document.querySelector('img.tcg-art')?.naturalWidth > 0);
  await fs.mkdir('.tmp-tcg', { recursive: true });
  await page.screenshot({ path: '.tmp-tcg/desktop.png' });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.emulateMedia({ reducedMotion: 'reduce' });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true, 'mobile overflow');
  assert.equal(await page.locator('.tcg-card').first().evaluate(el => getComputedStyle(el).animationName), 'none');
  await page.locator('.tcg-card').first().scrollIntoViewIfNeeded();
  await page.screenshot({ path: '.tmp-tcg/mobile.png' });
  await page.getByRole('button', { name: 'Open next pack' }).click();
  assert.equal((await getSave())[0].packs.length, 2);
  await page.reload();
  await page.getByRole('button', { name: 'Resume', exact: true }).click();
  await page.getByRole('button', { name: 'Reveal card 1 of 11' }).waitFor();
  assert.equal((await getSave())[0].progress, 'One badge earned');
  assert.equal((await getSave())[0].name, 'Saved browser test');
  const fresh = await browser.newContext();
  const replay = await fresh.newPage();
  await replay.goto(page.url());
  await replay.getByRole('button', { name: 'Start Challenge', exact: true }).click();
  await replay.getByRole('button', { name: 'Open Pack', exact: true }).click();
  await replay.getByRole('button', { name: 'Reveal all', exact: true }).click();
  const replaySave = await replay.evaluate(key => JSON.parse(localStorage.getItem(key)), key);
  assert.deepEqual(replaySave[0].packs[0].cards, first);
  await fresh.close();
  await page.getByRole('button', { name: 'Saved challenges / New run' }).click();
  page.once('dialog', d => d.accept('Renamed run'));
  await page.getByRole('button', { name: 'Rename', exact: true }).click();
  assert.equal((await getSave())[0].name, 'Renamed run');
  page.once('dialog', d => d.accept());
  await page.getByRole('button', { name: 'Delete', exact: true }).click();
  assert.deepEqual(await getSave(), []);
  assert.equal(await page.locator('meta[name=robots]').getAttribute('content'), 'index,follow,max-image-preview:large');
  assert.equal(requests.some(url => url.includes('api.tcgdex.net')), false, 'No runtime TCGdex API requests');
  assert.equal(requests.filter(url => /\/data\/tcg\/v1\/(?:base|gym|neo)\d\.json/.test(url)).every(url => url.endsWith('/base1.json')), true);
  // Fresh runs use Suggested; artwork is served locally.
  await page.goto(`${origin}/tcg-challenge`);
  assert.equal(await page.getByLabel('Reveal order').inputValue(), 'suggested-v1');
  await page.goto(`${origin}/tcg-challenge?game=crystal&set=neo1&seed=73A9A788&model=v1&order=historical-v1`);
  await page.getByRole('button', { name: 'Start Challenge', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('.tcg-wrapper-button img')?.naturalWidth > 0);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
  await page.locator('.tcg-sealed-pack').scrollIntoViewIfNeeded();
  await page.screenshot({ path: '.tmp-tcg/sealed-mobile.png' });
  await page.getByRole('button', { name: 'Open sealed booster' }).click();
  await page.waitForFunction(() => document.querySelector('.tcg-card-back img')?.naturalWidth > 0);
  const original = (await getSave())[0].packs[0].cards;
  assert.deepEqual(original.map(c => ['common', 'energy', 'uncommon'].includes(c.pool) ? c.pool : 'rare'), ['energy', 'rare', 'uncommon', 'uncommon', 'uncommon', ...Array(6).fill('common')]);
  await page.getByRole('button', { name: 'Reveal card 1 of 11' }).click();
  await page.getByLabel('Reveal order for next pack').selectOption('suggested-v1');
  assert.deepEqual((await getSave())[0].packs[0].cards, original, 'Changing order must preserve the opened pack');
  await page.reload();
  await page.getByRole('button', { name: 'Resume', exact: true }).click();
  await page.getByRole('button', { name: 'Reveal card 2 of 11' }).waitFor();
  await page.setViewportSize({ width: 1365, height: 900 });
  await page.locator('.tcg-card-back').scrollIntoViewIfNeeded();
  await page.screenshot({ path: '.tmp-tcg/card-back-desktop.png' });
  await page.getByRole('button', { name: 'Reveal all', exact: true }).click();
  await page.getByRole('button', { name: 'Open sealed booster' }).click();
  assert.equal(['rare', 'holo', 'secret', 'shining'].includes((await getSave())[0].packs[1].cards.at(-1).pool), true);
  assert.deepEqual(errors, []);
  console.log('TCG browser checks passed: reveal/resume, journal, team, game learnsets, TM rewards, replay, rename/delete, SEO, mobile, reduced motion, no runtime API downloads.');
} finally { await browser.close(); }
